esphome:
  name: control-temperatura
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "Nume_WiFi"
  password: "Parola_WiFi"
  ap:
    ssid: "ESP32-Setup"
    password: "12345678"

api:
web_server:
  port: 80
ota:

i2c:
  sda: 21
  scl: 22
  scan: true

sensor:
  - platform: max6675
    name: "Temperatura Termocupla"
    cs_pin: 5
    update_interval: 2s

  - platform: resistance
    id: pt100_resistance
    sensor: adc_sensor
    configuration: UPSTREAM
    resistor: 430.0Ω
    reference_voltage: 3.3V
    name: "Rezistenta PT100"
    unit_of_measurement: "Ω"
    accuracy_decimals: 2

  - platform: ntc
    sensor: pt100_resistance
    calibration:
      b_constant: 9990
      reference_temperature: 25°C
      reference_resistance: 100.0Ω
    name: "Temperatura Ambientala"

  - platform: adc
    pin: 36
    id: adc_sensor

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: GPIO16
    address: 0x3C
    lambda: |-
      it.printf(0, 0, id(font), "T: %.1f°C", id(temperatura_max6675).state);
      it.printf(0, 20, id(font), "Amb: %.1f°C", id(temperatura_ambientala).state);

switch:
  - platform: gpio
    pin: 23
    name: "Control Incalzire"
    id: incalzire

time:
  - platform: sntp
    id: sntp_time

font:
  - file: "arial.ttf"
    id: font
    size: 12

logger:
