CONFIG_ESP32_USE_UNSUPPORTED_REVISION=y

CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=80000000

CONFIG_LOG=y
CONFIG_SERIAL=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y

CONFIG_ADC=y
CONFIG_ADC_ESP32=y
CONFIG_NEWLIB_LIBC=y
CONFIG_FPU=y

# Driver Ecran & Interfață text
CONFIG_I2C=y
CONFIG_DISPLAY=y
CONFIG_SSD1306=y
CONFIG_CHARACTER_FRAMEBUFFER=y
CONFIG_CFB_LOG_LEVEL_ERR=y

# Driver Senzor Termocuplă MAX6675
CONFIG_SPI=y
CONFIG_SENSOR=y
CONFIG_MAX6675=y

# Păstrăm numărul întreg așa cum este
CONFIG_THERMAL_ADC_CHANNEL=3

# Adăugăm ghilimele pentru valorile string interpretate ca float
CONFIG_THERMAL_NTC_RESISTOR_FIXED="9990.0"
CONFIG_THERMAL_NTC_COEFF_A="0.001129148"
CONFIG_THERMAL_NTC_COEFF_B="0.000234125"
CONFIG_THERMAL_NTC_COEFF_C="0.0000000876741"