name: Zephyr Build CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: app 

      - name: Initialize West
        run: |
          west init -m https://github.com/zephyrproject-rtos/zephyr --mr v3.5.0 zephyr_ws
          cd zephyr_ws
          west update
          west zephyr-export
          pip install -r zephyr/scripts/requirements.txt

      - name: Build Firmware
        run: |
          export ZEPHYR_BASE=$(pwd)/zephyr_ws/zephyr
          # Folosim numele exact raportat de west boards
          west build -p always -b doit_esp32_devkit_v1 app/Software

      - name: Archive Firmware Binar
        uses: actions/upload-artifact@v4
        with:
          name: zephyr-bin
          path: build/zephyr/zephyr.bin